packages:
  branch_codenames:
    master: bionic-unstable
    production: bionic-stable

jobs:
  apt-s3:
    builder: "make"
    base: "quay.io/madebymany/build-bases:bionic"
    build_depends:
      - "libssl-dev"
      - "libcurl4-openssl-dev"
      - "libapt-pkg-dev"
    packages:
      - type: debian
        name: apt-transport-s3
        depends:
          - libcurl4-openssl-dev
          - libapt-pkg-dev
        repos:
          - mxm-public
        target: install
        conflicts:
          - "/usr/lib/apt/methods/s3"
